In [1]:
import numpy as np

<span style="font-size: 16px;">Part a</span>

In [4]:
M = np.array([
    [1, 0, 3],
    [3, 7, 2],
    [2, -2, 8],
    [0, -1, 1],
    [5, 8, 7]
])

In [6]:
#M^TM
M_transpose = M.T
MT_M = np.dot(M_transpose, M)
print("M^T M = \n", MT_M)

M^T M = 
 [[ 39  57  60]
 [ 57 118  53]
 [ 60  53 127]]


In [7]:
#MM^T
M_MT = np.dot(M, M_transpose)
print("MM^T = \n", M_MT)

MM^T = 
 [[ 10   9  26   3  26]
 [  9  62   8  -5  85]
 [ 26   8  72  10  50]
 [  3  -5  10   2  -1]
 [ 26  85  50  -1 138]]


<span style="font-size: 16px;">Part b</span>

In [8]:
eigenvals_MT_M = np.linalg.eigvals(MT_M)
eigenvals_MT_M = np.sort(eigenvals_MT_M)[::-1]
print("Eigenvalues of M^T M:")
print(eigenvals_MT_M)

Eigenvalues of M^T M:
[ 2.14670489e+02  6.93295108e+01 -4.65183174e-15]


In [10]:
eigenvals_M_MT = np.linalg.eigvals(M_MT)
eigenvals_MT_M = np.sort(eigenvals_M_MT)[::-1]
print("\nEigenvalues of MM^T:")
print(eigenvals_M_MT)


Eigenvalues of MM^T:
[ 2.14670489e+02 -1.98884150e-14  6.93295108e+01 -1.02373098e-15
  2.14922736e-15]


<span style="font-size: 16px;">Part c</span>

In [15]:
eigenvals_MT_M, eigenvecs_MT_M = np.linalg.eigh(MT_M)

idx_MT_M = eigenvals_MT_M.argsort()[::-1]
eigenvals_MT_M = eigenvals_MT_M[idx_MT_M]
eigenvecs_MT_M = eigenvecs_MT_M[:, idx_MT_M]

eigenvals_M_MT, eigenvecs_M_MT = np.linalg.eigh(M_MT)

idx_M_MT = eigenvals_M_MT.argsort()[::-1]
eigenvals_M_MT = eigenvals_M_MT[idx_M_MT]
eigenvecs_M_MT = eigenvecs_M_MT[:, idx_M_MT]

print("\nEigenvectors of M^T M (columns):")
print(eigenvecs_MT_M)

print("\nEigenvectors of MM^T (columns):")
print(eigenvecs_M_MT)


Eigenvectors of M^T M (columns):
[[ 0.42615127  0.01460404  0.90453403]
 [ 0.61500884  0.72859799 -0.30151134]
 [ 0.66344497 -0.68478587 -0.30151134]]

Eigenvectors of MM^T (columns):
[[-0.16492942  0.24497323  0.0696646   0.04259611  0.95190273]
 [-0.47164732 -0.45330644  0.71521789  0.24438161 -0.02833866]
 [-0.33647055  0.82943965  0.32430825 -0.09375112 -0.29129423]
 [-0.00330585  0.16974659 -0.22438689  0.95699161 -0.07065942]
 [-0.79820031 -0.13310656 -0.57278695 -0.11764774 -0.05685965]]


<span style="font-size: 16px;">Part d</span>

In [17]:
U, s, VT = np.linalg.svd(M)
U = U[:, :2]
s = s[:2]
VT = VT[:2, :]

Sigma = np.zeros((2, 3))
Sigma[0, 0] = s[0]
Sigma[1, 1] = s[1]

print("U (5x2):")
print(U)
print("\nΣ (2x3):")
print(Sigma)
print("\nV^T (2x3):")
print(VT)

U (5x2):
[[-0.16492942 -0.24497323]
 [-0.47164732  0.45330644]
 [-0.33647055 -0.82943965]
 [-0.00330585 -0.16974659]
 [-0.79820031  0.13310656]]

Σ (2x3):
[[14.65163776  0.          0.        ]
 [ 0.          8.32643446  0.        ]]

V^T (2x3):
[[-0.42615127 -0.61500884 -0.66344497]
 [ 0.01460404  0.72859799 -0.68478587]]


<span style="font-size: 16px;">Part e</span>

In [19]:
U, s, VT = np.linalg.svd(M)
s[1:] = 0
M_approx = np.dot(U[:, :1] * s[0], VT[0:1, :])

print("1D approximation of M:")
print(M_approx)

1D approximation of M:
[[1.02978864 1.48616035 1.60320558]
 [2.94487812 4.24996055 4.58467382]
 [2.10085952 3.031898   3.27068057]
 [0.02064112 0.02978864 0.0321347 ]
 [4.9838143  7.19249261 7.75895028]]
